// Every user-facing string, in one place. English only.
export const strings = {
  appName: "Note Shote",
  somethingWentWrong: "Something went wrong. Please try again.",
  cancel: "Cancel",
  retry: "Try again",
  save: "Save",
  delete: "Delete",

  auth: {
    email: "Email",
    password: "Password",
    passwordHint: "At least 8 characters.",
    signInTitle: "Welcome back",
    signInSubtitle: "Sign in to open your notes.",
    signUpTitle: "Create your account",
    signUpSubtitle: "Only invited emails can sign up.",
    logIn: "Log in",
    signUp: "Sign up",
    logOut: "Log out",
    noAccount: "No account yet? Sign up",
    haveAccount: "Already have an account? Log in",
  },

  list: {
    views: { notes: "Notes", archive: "Archive", trash: "Trash" },
    search: "Search notes",
    newNote: "New note",
    settings: "Settings",
    untitled: "Untitled",
    pinned: "Pinned",
    loading: "Loading…",
    emptyNotes: "No notes yet. Tap + to write one.",
    emptyArchive: "Nothing archived.",
    emptyTrash: "The trash is empty.",
    noResults: "No notes match your search.",
    searchHint: "Searches every note, including Archive and Trash, by whole words and word starts.",
    emptyTrashButton: "Empty trash",
    emptyTrashTitle: "Empty the trash?",
    emptyTrashDescription: "Every note in the trash is deleted forever. This can't be undone.",
    trashHint: "Notes in the trash are deleted after 30 days.",
  },

  note: {
    titlePlaceholder: "Title",
    bodyPlaceholder: "Write in Markdown…",
    emptyBody: "Empty note. Tap Edit to write.",
    saving: "Saving…",
    saved: "Saved",
    offline: "Offline",
    loading: "Loading…",
    edit: "Edit",
    done: "Done",
    preview: "Preview",
    pin: "Pin",
    unpin: "Unpin",
    archive: "Archive",
    unarchive: "Unarchive",
    tags: "Tags",
    copy: "Copy Markdown",
    copied: "Copied",
    trash: "Move to trash",
    restore: "Restore",
    deleteForever: "Delete forever",
    deleteForeverTitle: "Delete this note forever?",
    deleteForeverDescription: "It can't be restored afterwards.",
    inTrash: "This note is in the trash. Restore it to edit.",
    notFound: "This note doesn't exist or was deleted.",
    back: "Back to notes",
    tooLong: "Limit reached. Delete some text to keep typing.",
    size: (kb: string, maxKb: string) => `${kb} / ${maxKb} KB`,
    rawNotice:
      "This note has content the rich editor can't keep (code, tables, quotes, task lists…), so it's edited as raw Markdown.",
    linkTitle: "Link URL",
    linkPlaceholder: "https://",
    toolbar: {
      bold: "Bold",
      italic: "Italic",
      strike: "Strikethrough",
      h1: "Heading 1",
      h2: "Heading 2",
      h3: "Heading 3",
      bullets: "Bulleted list",
      numbers: "Numbered list",
      link: "Link",
      indent: "Indent",
      outdent: "Outdent",
    },
  },

  tabs: { notes: "Notes", tags: "Tags", search: "Search" },

  tags: {
    title: "Tags",
    emptyHint: "No tags yet. Tap + to add one, or add them from a note.",
    newTag: "New tag",
    newTagPlaceholder: "Tag name",
    add: "Add",
    none: "No tags yet.",
    rename: "Rename",
    renameTitle: "Rename tag",
    deleteTitle: (name: string) => `Delete “${name}”?`,
    deleteDescription: "It's removed from its notes. The notes stay.",
    count: (n: number) => (n === 1 ? "1 note" : `${n} notes`),
    done: "Done",
    emptyTag: "No notes have this tag.",
    tagNotFound: "This tag doesn't exist or was deleted.",
  },

  settings: {
    title: "Settings",
    account: "Account",
    signedInAs: "Signed in as",
    appearance: "Theme",
    themes: { light: "Light", dark: "Dark", system: "System" },
  },

  time: {
    justNow: "just now",
    minutes: (n: number) => `${n} min ago`,
    hours: (n: number) => `${n} h ago`,
    yesterday: "yesterday",
    days: (n: number) => `${n} days ago`,
  },

  // Server error codes (plain-string ConvexErrors).
  errors: {
    notAuthenticated: "Your session has expired. Please log in again.",
    notAllowed: "This account isn't allowed to use this app.",
    noteNotFound: "This note doesn't exist or was deleted.",
    tagNotFound: "That tag doesn't exist any more.",
    titleTooLong: "The title is over 200 characters.",
    bodyTooLong: "The note is over the 100 KB limit.",
    tooManyTags: "A note can have at most 20 tags.",
    tagNameInvalid: "Tag names are 1–50 characters.",
    tagNameTaken: "You already have a tag with that name.",
    notInTrash: "That note isn't in the trash.",
    invalidEmail: "Enter a valid email address.",
    passwordTooShort: "The password must be at least 8 characters.",
    invalidCredentials: "Wrong email or password.",
    accountExists: "An account with this email already exists. Log in instead.",
  } as Record<string, string>,
};
